export const portfolio = [
    {
        id: "1",
        image: 'https://i.ibb.co/WGy7tHd/A34-EC4-E2-2-B01-4767-BB67-23-FF81-BB692-B.png',
        name: 'Blend Battles',
        desc: `Blend Battles is a casual game in which the player has to merge the boys and girls on the beach to make them stronger and fight! In this game, you would need to position the beach boys and girls based on your strategy in the arena and overcome the opponent!`,
        genre: 'Casual',
        releaseDate: '8th August 2022',
        rating: 4.8,
        price: '0.00',
        link: "https://apps.apple.com/app/blend-battles-epic-battle/id1633086180"
    },
    {
        id: "2",
        image: 'https://i.ibb.co/7bV949D/0-DCE1-CA0-E9-DB-4968-9376-A2-DB7-B46-BF91.png',
        name: 'Beach Fight',
        desc: `Beach Fight is a pushing game where you will have to place the Pushers at the right time and push your opponent to the end and win. The player can choose from 3 different Bikini Girls and place them on track - the bigger the Pusher, the stronger the push - but also takes longer time to deploy - so choose and place them wisely!`,
        genre: 'Casual',
        releaseDate: '17th November 2021',
        rating: 4.8,
        price: '0.00',
        link: "https://apps.apple.com/us/app/beach-fight/id1593685370"

    },
    {
        id: "3",
        image: 'https://i.ibb.co/943czRq/unnamed-2.webp',
        name: 'People Money',
        desc: `Runner game with crowd formation with upgrade mechanics.`,
        genre: 'Racing',
        releaseDate: '2nd April 2023',
        rating: 4.5,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.games.PeopleMoney"
    },
    {
        id: "4",
        image: 'https://i.ibb.co/Lp3Wfn2/unnamed-1.webp',
        name: 'DMV Manager',
        desc: `Idle arcade game of DMV manager where you play as an office in-charge and serve multiple customers by printing vehicle's number plates.`,
        genre: 'Role Playing',
        releaseDate: '17th April 2023',
        rating: 4.7,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.creativefungames.dmvmanager"
    },
    {
        id: "5",
        image: 'https://i.ibb.co/tpvNpdB/unnamed-1.webp',
        name: 'Idle Pawsome Tycoon',
        desc: `Idle Pet Clinic is the ultimate game for animal lovers where the players take on the role of a compassionate veterinarian and can build their very own pet clinic. Players can provide essential services like grooming, bathing, vaccination, and nail cutting to adorable pets in need. `,
        genre: 'Casual',
        releaseDate: '11th July 2023',
        rating: 4.6,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.creativefungames.pawtoon"
    },
    {
        id: "6",
        image: 'https://i.ibb.co/1JcvHXs/unnamed-5.webp',
        name: 'Super Bro: Adventure Run Game',
        desc: `Super Bro Go is a fun running arcade game in which you have to save yourself from obstacles and reach the castle in every level. The game contain well-designed levels in order to trick the players with different challenges and obstacles that makes the game super fun.`,
        genre: 'Action / Platformer / Casual',
        releaseDate: '3rd January 2022',
        rating: 4.6,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.gamenotch.superbro.go.adventure.run"
    },
    {
        id: "7",
        image: 'https://i.ibb.co/Dzc6Tdk/Red-Jumping-Ball.webp',
        name: 'Red Jumping Roller Bounce Ball',
        desc: `The Red Jumping Ball game is a gun game where the player has to clear the land, defeat the enemies, collect the stars, and then fight with the bosses in order to save their friends from red jumping ball games. Save your friends from the evil bosses who kidnapped them and their companions in an adventure ball game. In this bounce tales game, all you need to do is to save yourself from obstacles, challenging traps, moving lasers, and enemies with thrilling powers.`,
        genre: 'Casual',
        releaseDate: '7th February 2023',
        rating: 4.5,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.gn.jumping.ballgames"
    },
    {
        id: "8",
        image: 'https://i.ibb.co/ydqYbcn/unnamed-5.webp',
        name: 'Police Chase 2 - Thief Simulator',
        desc: `A really interesting and amusing game for arcade lovers. Gets your minds refreshed and active to escape the police cars. Chased by police cars, it’s not uncomplicated to run off of police wheels.`,
        genre: 'Arcade',
        releaseDate: '7th April 2020',
        rating: 5,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.futuristicGames.PoliceChase2"
    },
    {
        id: "9",
        image: 'https://i.ibb.co/HGDtGc4/DA964-B52-5-C49-40-EB-8692-93628-AEBB320.png',
        name: 'Tap Hop Adventure',
        desc: `Embark on a hooping adventure with "Tap Hop Adventure" – Test your timing and skill as you navigate an array of unique balls through diverse environments and tricky obstacles, aiming to score by getting them into suspended hoops.`,
        genre: 'Casual',
        releaseDate: '31st August 2023',
        rating: 4.5,
        price: '0.00',
        link: "https://apps.apple.com/us/app/tap-hop-adventure/id6451442430"
    },
    {
        id: "10",
        image: 'https://i.ibb.co/0rLqphQ/unnamed-2.webp',
        name: 'Windy Paratroopers',
        desc: `Adjust and aim with your catapult, and release to shoot your paratroopers.. Open your parachute and navigate to land score a perfect landing and fight enemies to take over an island.`,
        genre: 'Arcade',
        releaseDate: '3rd Ausgust 2022',
        rating: 4.8,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.tinykrakengames.windy.paratroppers",
        publisher: "Tiny Kraken Games"
    },
    {
        id: "11",
        image: 'https://i.ibb.co/mzVWQkd/unnamed.webp',
        name: 'Magnet Man',
        desc: `The Magnet man attracts everything towards himself while escaping giants. Release to blast all objects back and kill the giants chasing you.`,
        genre: 'Arcade',
        releaseDate: '10th October 2022',
        rating: 4.8,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.tinykrakengames.magnet.man",
        publisher: "Tiny Kraken Games"
    },
    {
        id: "12",
        image: 'https://i.ibb.co/W5yKqQT/unnamed-1.webp',
        name: 'Earthquake Tester',
        desc: `Make the building safe by adding structural parts. Tap the earthquake button to test your structure. Win and earn if it does not fall.`,
        genre: 'Arcade',
        releaseDate: '6th September 2022',
        rating: 4.9,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.tk.EarthQuake",
        publisher: "Tiny Kraken Games"
    },
    {
        id: "13",
        image: 'https://i.ibb.co/vvsvPMc/unnamed.webp',
        name: 'Cube Battleship',
        desc: `Build a base with your deck. Place your buildings on the map to attack and defend your territory. Use your weapon cards to aim and attack on the enemy grounds to conquer. Protect your King, castle and defenses, level up your heroes deck and win PvP battles!`,
        genre: 'Strategy',
        releaseDate: '8th December 2022',
        rating: 5,
        price: '0.00',
        link: "https://play.google.com/store/apps/details?id=com.tinykrakengames.secret.wars",
        publisher: "Tiny Kraken Games"
    },
    // {
    //     id: "10",
    //     image: 'https://i.ibb.co/fCWJHPn/48-A36500-AC75-4-A8-F-A542-CA406705-A0-D8.png',
    //     name: 'Save the Castle',
    //     desc: `Save the Castle is the best combination of action, strategy, and puzzle in one game! You will enjoy playing this game and build your own stickman empire!`,
    //     genre: 'Casual / Merge Mechanics',
    //     releaseDate: '3rd April 2023',
    //     rating: 4.6,
    //     price: '0.00',
    //     link: "https://apps.apple.com/us/app/save-the-castle/id1665862827"
    // },
];